language: python
python:
  - "3.4"
virtualenv:
system_site_packages: true
install:
  - pip install -r reqs.pip
before_script: 
  - sudo apt-get -y update
  - wget https://github.com/mozilla/geckodriver/releases/download/v0.24.0/geckodriver-v0.24.0-linux64.tar.gz -O /tmp/geckodriver.tar.gz
  - sudo tar -C /usr/local/bin/ -xzf /tmp/geckodriver.tar.gz
  - sudo chmod 755 /usr/local/bin/geckodriver
script:
  - python -m unittest discover -p "test*.py"