language: python
python:
  - "3.4"
virtualenv:
system_site_packages: true
install:
  - pip install -r reqs.pip
before_script: 
  - sudo apt-get -y update
  - sudo apt-get -y install firefox
  - firefox -v
  - cd /tmp
  - wget https://github.com/mozilla/geckodriver/releases/download/v0.24.0/geckodriver-v0.24.0-linux64.tar.gz -O /tmp
  - sudo tar -xvzf geckodriver-v0.24.0-linux64.tar.gz
  - sudo tar -C /usr/local/bin/ -xzf /tmp/geckodriver
  - sudo chmod +x /usr/local/bin/geckodriver
  - export PATH=$PATH:/usr/local/bin/geckodriver
script:
  - python -m unittest discover -p "test*.py"