language: python
python:
  - "2.7"
  - "3.4"
virtualenv:
system_site_packages: true
install:
  - pip install -r reqs.pip
before_script: 
  - wget "https://chromedriver.storage.googleapis.com/2.41/chromedriver_linux64.zip"
  - unzip chromedriver_linux64.zip
  - sudo mv chromedriver /usr/bin/chromedriver
  - sudo chown root:root /usr/bin/chromedriver
  - sudo chmod +x /usr/bin/chromedriver
  - export PATH=$PATH:/usr/bin/chromedriver
script:
 - python -m unittest discover -p "test*.py"