language: python
python:
  - "3.4"
virtualenv:
system_site_packages: true
install:
  - pip install -r reqs.pip
before_script: 
  - wget https://github.com/mozilla/geckodriver/releases/download/v0.24.0/geckodriver-v0.24.0-linux64.tar.gz -O /tmp/geckodriver.tar.gz
  - tar -C /opt -xzf /tmp/geckodriver.tar.gz
  - chmod 755 /opt/geckodriver
  - ln -fs /opt/geckodriver /usr/local/bin/geckodriver
script:
  - python -m unittest discover -p "test*.py"