language: python
python:
  - "3.4"
virtualenv:
system_site_packages: true
install:
  - sudo apt-get install python-pip
before_script:
  - sudo apt-get -y update
  - sudo apt-get -y install firefox
  - firefox -v
  - pip install selenium
  - cd /tmp
  - wget https://github.com/mozilla/geckodriver/releases/download/v0.24.0/geckodriver-v0.24.0-linux64.tar.gz
  - sudo tar -xvf geckodriver-v0.24.0-linux64.tar.gz
  - sudo mv geckodriver /usr/local/bin
  - sudo chmod +x /usr/local/bin/geckodriver
  - export PATH=$PATH:/usr/local/bin/geckodriver
  - cd /home/travis/build/dimien/the-internet-selenium-py
script:
  - sudo python -m unittest discover -p "test*.py"